[package]
name = "millsrs"
version = "0.1.0"
authors = ["Mario Geiger <geiger.mario@gmail.com>"]

[dependencies]
negamax = { git = "https://github.com/mariogeiger/negamax" }
lazy_static = "1.1.0"
rand = "0.5"
rustty = "*"
